### ISSUE TITLE
Uniform payload API

### ISSUE THREAD

**Issue by zackw** [TheTorProject/stegotorus#1]
We should make the payload-generation and encoding API uniform.  Something like this:

```
struct payload
{
  type_code?;
  string data;
  virtual get_capacity();
  virtual encode();
  virtual decode();
}
```

Also, "JS" and "JS in HTML" should be distinct operation modes (so we can, in future, just have an "HTML" mode).

**Comment by vmon** [comment]
This is done. 
 - All payload types are inherited from  FileStegMode class which implements all above methods.
 - HTMLSteg is child of JSSteg and provide distinct type.
