### ISSUE TITLE
Master tor-improve merge needs checkup

### ISSUE THREAD

**Issue by BaronWolfenstein** [TheTorProject/stegotorus#12]
Current master is not building (the one that was a result of merging tor-improve into) -- was going to use it to check baseline payload generation 

src/protocol/chop.cc:417:2: error: #error "Key agreement not yet implemented"
 #error "Key agreement not yet implemented"
  ^
depbase=`echo src/protocol/null.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    g++    -I. -I./src -I./src/steg -I./src/steg/http_steg_mods -I./src/test/gtest -I./src/test/gtest/include     -Werror -Wall -Wextra -Wno-missing-field-initializers -Wformat=2 -std=c++0x -g -O2 -std=gnu++11 -MT src/protocol/null.o -MD -MP -MF $depbase.Tpo -c -o src/protocol/null.o src/protocol/null.cc &&\
    mv -f $depbase.Tpo $depbase.Po
src/protocol/chop.cc: In member function ‘void {anonymous}::chop_config_t::init_handshake_encryption()’:
src/protocol/chop.cc:425:60: error: ‘passphrase’ was not declared in this scope
     kgen = key_generator::from_passphrase((const uint8_t _)passphrase,
                                                            ^
src/protocol/chop.cc: In member function ‘virtual circuit_t_ {anonymous}::chop_config_t::circuit_create(size_t)’:
src/protocol/chop.cc:455:43: error: expected primary-expression before ‘...’ token
     kgen = key_generator::from_passphrase(...);

**Comment by vmon** [comment]
Closing. Master currently builds.
