### ISSUE TITLE
JS segfaulting for type 1 (pure JS)

### ISSUE THREAD

**Issue by BaronWolfenstein** [TheTorProject/stegotorus#15]
temp_pdf_debugging branch is latest functioning one - can probably hove this off onto f--stegize-js if necessary

find_content_type is returning zero, cant find end of header, let alone content type
On server, HTML works fine, but JS gets

67.2680 [debug] pick_appropriate_cover_payload: SERVER found the next HTTP response template with size 10010
67.2680 [debug] http_server_transmit: coping body of 9876 size
67.2680 [debug] http_server_transmit: SERVER embeding data1 with length 259 into type 1
67.2694 [warn] decode: ERROR: Invalid content type (0)
67.2704 [warn] http_server_transmit: decoding cannot recovers the encoded data consistantly for type 1
67.2705 [warn] send: <1.4> failed to transmit block
67.2705 [info] circuit_send: <1> error during transmit
67.2706 [warn] close: <1> destroying active circuit: fin-- eof- ds=1
67.2706 [debug] downstream_flush_cb: <0.4> 0 bytes still to transmit (reached EOF) (received EOF) (no circuit)
67.2707 [debug] close: <0.4> closing connection; 1 remaining
67.2708 [debug] close: <1> deleting circuit 723844364 from the table
67.2708 [debug] close: <1> closing circuit; 1 remaining
67.2709 [debug] close_cleanup_cb: cleaning up 1 circuits and 1 connections
67.3718 [info] server_listener_cb: 127.0.0.1:5000: new connection to server from 127.0.0.1:32909
67.3719 [debug] conn_create: <0.5> new connection
67.3719 [debug] downstream_flush_cb: <0.5> 0 bytes still to transmit (no circuit) (never received)
67.3725 [debug] downstream_read_cb: <0.5> 456 bytes available
67.3726 [debug] http_server_receive: <0.5> SERVER received request header of length 452
67.3726 [debug] http_server_receive: Cookie: DP0kK22I9=CEySOeDMgdCX-D585NhQF3vWTtvTDQRacgAAAAEAAAABgEAAAAAAAAAAAA;AAAAAA=AAAAAAAAAAA;AAAAA=A;AAAA=..

67.3726 [debug] transmit_soon: <0.5> must send within 100 milliseconds
67.3727 [debug] verify_and_extract: retrieved circ id 723844364
67.3727 [debug] recv_handshake: <0.5> stale circuit
67.3727 [debug] send: <0.5> must send (no upstream)
67.3727 [debug] transmit_room: <0.5> checking available capacity for type 1
67.3728 [debug] get_payload: contentType = 1, initTypePayload = 1, typePayloadCount = 280
67.3728 [debug] get_payload: first payload size=11789, best payload size=10010, num candidate=100

67.3728 [debug] pick_appropriate_cover_payload: SERVER found the next HTTP response template with size 10010
67.3729 [debug] http_server_transmit: coping body of 9876 size
67.3729 [debug] http_server_transmit: SERVER embeding data1 with length 41 into type 1

[error] Segmentation fault at 000000000923f538

**Comment by BaronWolfenstein** [comment]
see comment https://github.com/TheTorProject/stegotorus/commit/483b7a5bfb23bd806f9b2e599b6c4a1fe381edd5#commitcomment-9383606

http://stackoverflow.com/questions/2855121/what-is-the-purpose-of-using-pedantic-in-gcc-g-compiler

**Comment by vmon** [comment]
Closing. All new StegModes are propely integrated as FileStegMod and non through SegFault.
