### ISSUE TITLE
不懂

### ISSUE THREAD

**Issue by dong910325** [TheTorProject/stegotorus#17]
Dec 15 19:27:39.393 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Dec 15 19:27:39.394 [notice] Read configuration file "/data/data/org.torproject.android/app_bin/torrc".
Dec 15 19:27:39.394 [notice] Read configuration file "/data/data/org.torproject.android/app_bin/torrc.custom".
Dec 15 19:27:39.404 [warn] Skipping obsolete configuration option 'WarnUnsafeSocks'
Dec 15 19:27:39.404 [warn] Skipping obsolete configuration option 'DNSListenAddress'
Dec 15 19:27:39.410 [notice] Opening Socks listener on 127.0.0.1:0
Dec 15 19:27:39.410 [notice] Socks listener listening on port 52182.
Dec 15 19:27:39.410 [notice] Opening DNS listener on 127.0.0.1:5400
Dec 15 19:27:39.411 [notice] Opening Transparent pf/netfilter listener on 127.0.0.1:9040
Dec 15 19:27:39.411 [warn] Could not bind to 127.0.0.1:9040: Address already in use. Is Tor already running?

**Comment by vmon** [comment]
Closed. This seems to be double running of Tor and is not a Stegotorus issue.

**Comment by vmon** [comment]
This seems to be double running of Tor and is not a Stegotorus issue. Resolved #17.

**Comment by vmon** [comment]
This seems to be double running of Tor and is not a Stegotorus issue. resolved #17.

**Comment by vmon** [comment]
resolved #17

**Comment by vmon** [comment]
This closes #17
