### ISSUE TITLE
Stegotorus needs a config file

### ISSUE THREAD

**Issue by zackw** [TheTorProject/stegotorus#6]
This thing where we stack everything on the command line has become just too unwieldy.

A config file would enable all sorts of goodness (mostly via being able to pass parameters to steg modules):
- getting rid of the "repeat the IP address N times" thing for controlling simultaneous connections
- merging nosteg and nosteg_rr
- moving the trace files around
- etc

**Comment by vmon** [comment]
Implemented. see modus_operandi.cc

**Comment by vmon** [comment]
Implemented. see modus_operandi.cc.
