### ISSUE TITLE
Double closing a circuit in send and check_for_eof make assertion failure

### ISSUE THREAD

**Issue by vmon** [TheTorProject/stegotorus#9]
We might want to check for "being closed" before the eof check. But more importantly we should not close a connection for too many open file error, because we can wait and more file probably will be available (while taking side measure like closing connections more aggressively i.e shorter axe timer).

2854.3218 [debug] send: <1941> 14 dead cycles
2854.3219 [info] create_one_outbound_connection: <1941> trying to connect to 127.0.0.1:5000
2854.3220 [info] create_one_outbound_connection: <1941> connection to 127.0.0.1:5000 failed: Too many open files
2854.3220 [warn] create_outbound_connections: <1941> no outbound connections were successful
2854.3221 [debug] downstream_flush_cb: <0.60159> 0 bytes still to transmit (reached EOF) (sent EOF) (no circuit) (never received)
2854.3221 [debug] downstream_flush_cb: <0.60403> 0 bytes still to transmit (reached EOF) (sent EOF) (no circuit) (never received)
2854.3221 [debug] downstream_flush_cb: <0.60226> 0 bytes still to transmit (reached EOF) (sent EOF) (no circuit) (never received)
2854.3222 [debug] downstream_flush_cb: <0.60380> 0 bytes still to transmit (reached EOF) (sent EOF) (no circuit) (never received)
2854.3222 [debug] downstream_flush_cb: <0.60457> 0 bytes still to transmit (reached EOF) (sent EOF) (no circuit) (never received)
2854.3223 [debug] downstream_flush_cb: <0.60284> 0 bytes still to transmit (reached EOF) (sent EOF) (received EOF) (no circuit)
2854.3223 [debug] close: <0.60284> closing connection; 0 remaining
2854.3224 [debug] close: <1941> deleting circuit 4070651211 from the table
2854.3224 [debug] close: <1941> closing circuit; 101 remaining
2854.3224 [debug] check_for_eof: <1941> sent and received FIN
2854.3225 [debug] close: <1941> deleting circuit 4070651211 from the table
2854.3225 [error] close: assertion failure at src/protocol/chop.cc:407: out->second == this

**Comment by BaronWolfenstein** [comment]
This may become an issue when testing the new handshake

**Comment by vmon** [comment]
Closing. We don't do eof check on closed connections.
